### ISSUE TITLE
Can't rewatch Amalgamate cutscene

### ISSUE THREAD

**Issue by ErikHaag** [icwass/ReductiveMetallurgyCampaign#3]
I wasn't expecting this cutscene to occur, and wasn't looking. And I can't find a way to retrigger the cutscene even when looking through files

**Comment by icwass** [comment]
In the same folder where your solution files are (should be the folder `NonSteamUser/`) there is a `save.dat` file. This file can be edited with a text editor like Notepad.

If you've seen the cutscene already, then there will be a line that reads `RMC-FinaleSeen = True`. You can either delete this line or replace it with `RMC-FinaleSeen = False`, and that will allow you to watch the scene once again the next time you boot the game.
